[project]
name = "shortcomings-cli"
version = "0.3.6"
description = "Maintain and search project features and shortcomings"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "typer>=0.24.0",
    "pyyaml>=6.0",
]

[tool.uv]
exclude-newer = "30 days"

[project.scripts]
shortcomings = "shortcomings.main:app"

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 120
target-version = "py312"

[tool.pytest.ini_options]
pythonpath = ["src"]

[dependency-groups]
dev = [
    "coverage>=7.13.5",
    "pytest>=9.0.2",
    "ruff>=0.15.4",
    "ty>=0.0.19",
]
